// !!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!
// !!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!

#pragma once

extern "C" const unsigned long long luisa_compute_hip_hiprt_library_gfx1200_size;
extern "C" const unsigned char luisa_compute_hip_hiprt_library_gfx1200[];
