// !!!!!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!!!!
// !!!!!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!!!!

extern "C" const unsigned char luisa_cuda_codegen_libdevice_bitcode[486168];
