# This script generates the device library bitcode for CUDA backend using LLVM.

from shutil import which
from pathlib import Path
from typing import TextIO


def embed_bitcode(input_path: Path, output_header_file: TextIO, output_cpp_file: TextIO, array_name: str):
    with open(input_path, "rb") as f:
        data = f.read()
    # print declaration in header
    output_header_file.write(f"extern \"C\" const unsigned char {array_name}[{len(data)}];\n")
    # print definition in cpp
    output_cpp_file.write(f"\nextern \"C\" const unsigned char {array_name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_array = ", ".join(f"0x{b:02x}u" for b in chunk)
        output_cpp_file.write(f"    {hex_array},\n")
    output_cpp_file.write("};\n")


def find_nvvm_libdevice() -> Path:
    nvcc_path = which("nvcc")
    assert nvcc_path
    nvvm_libdevice_path = Path(nvcc_path).parent.parent / "nvvm" / "libdevice"
    assert nvvm_libdevice_path.exists()
    libs = sorted(nvvm_libdevice_path.glob("libdevice.*.bc"), key=lambda x: int(x.name.split(".")[1]))
    assert libs
    return libs[-1]


def main():
    output_dir = Path(__file__).parent
    with open(output_dir / "cuda_codegen_llvm_device_bitcode.h", "w") as header_file, \
            open(output_dir / "cuda_codegen_llvm_device_bitcode.cpp", "w") as cpp_file:
        header_file.write("// !!!!!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!!!!\n")
        header_file.write("// !!!!!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!!!!\n\n")
        cpp_file.write("// !!!!!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED !!!!!!!!!!!!\n")
        cpp_file.write("// !!!!!!!!!!!!    PLEASE DO NOT EDIT IT MANUALLY    !!!!!!!!!!!!\n\n")
        cpp_file.write("// clang-format off\n")
        # embed libdevice
        embed_bitcode(find_nvvm_libdevice(), header_file, cpp_file, "luisa_cuda_codegen_libdevice_bitcode")
        # TODO: other bitcode
        cpp_file.write("\n// clang-format on\n")


if __name__ == "__main__":
    main()
